language: python
python:
- '2.7.11'
- '3.5.1'
cache: pip
env:
    matrix:
        - DJANGO="Django<1.9,>=1.8"
        - DJANGO="Django<1.10,>=1.9"
install:
- pip install -r socialprofile_demo/requirements_dev.txt
script: coverage run --source=socialprofile,socialprofile_demo --rcfile=devscripts/checkers/coveragerc
  manage.py test
after_success: coveralls
deploy:
  provider: pypi
  user: Tim.White
  password:
    secure: QD4mZ/IKSeyNr52+TqZQItVDh3Z/0nVi/D3MweSJq7pebHo5GH1YuoYZecSG9mqMppqbZK1VsXbag9Zml/UuP9bSLsce2A4g01Z+kz7zgFRpU0//MJ7Aj3JXfKObdwoviailZcyp+JqGygCS1Xbfk8tpIJimFrwu47Ibmz61Sjw=
  on:
    repo: cyface/django-socialprofile
