language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r socialprofile_demo/requirements_dev.txt --download-cache $HOME/.pip-cache"
# command to run tests
script: "python manage.py jenkins socialprofile --coverage-rcfile=devscripts/checkers/coveragerc"
script:
  coverage run --source=socialprofile,socialprofile_demo --rcfile=devscripts/checkers/coveragerc manage.py test
sudo: false
after_success:
  coveralls
